# Generated by Django 3.0 on 2021-02-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='albums', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'trabajos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('paquete', models.CharField(max_length=200)),
                ('tarjeta', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=200)),
                ('modem', models.CharField(max_length=200)),
                ('lbn', models.CharField(max_length=200)),
                ('instalacion', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
            ],
        ),
    ]
